---
name: Deploy to DigitalOcean
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}
          script: >
            cd /home/gopal/Documents/Django_For_Numerical_Methods

            git pull origin main

            source /home/gopal/Documents/Django_For_Numerical_Methods/venv/bin/activate

            python manage.py migrate

            python manage.py collectstatic --noinput

            sudo systemctl restart gunicorn

            sudo systemctl restart nginx

